spring:
  datasource:
    url: jdbc:sqlserver://helloworld-srv.database.windows.net:1433;database=helloworld-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect